// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imxifvlwpmumubummwpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlteGlmdmx3cG11bXVidW1td3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTEyMzIsImV4cCI6MjA2OTI4NzIzMn0.sDp676Ge-bSNMOh58ZJoF65IY-4B6dgSKIDz7mQ-hDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});